./" author :zjb 
.TH Hello 1 "2020-6-24" "Linux" "Hello Maunal"        /"  注意"2008-4-2"会被显示在
                                                                                           /"  文件最后一行（页脚）的中部，
                                                                                          /"  "GNU"在最后一行的行首    
                                                                                          /"  "GNU tools"在第一行（页眉）的中部

.SH Name                                         
 hello /- GNU hello                          /"  - 必须用 /- 转义
.SH SYNOPSIS
.B hello
.RB [/fB/-help/fR]                          /".RB为罗马字体+粗体交替显示
.RB [/-a]
.sp                                         /" 空行
.SH DESCRIPTION
this is an example of man page.                
.sp
/&.is at begin of a line.                   /" 行首的.要用/&.转义   
.TP                                       
 /fI italic word! /fR                       
.sp
.sp
.SH AUTHOR
.TP 3     
laomai                        
http://blog.csdn.net/zjbhello
